# Generated by Django 4.1 on 2022-08-31 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(limit_value=5)]),
        ),
    ]
